### ISSUE TITLE
decryption not working on android 12/13

### ISSUE THREAD

**Issue by pedroborraz** [TeamWin/android_device_motorola_guamp#2]
## Problem:
On a gsi android 12 or 13 they have errors in encryption. In android 12 the user's pin is requested but even providing returns an error, it is only possible if remove the OS password. On android 13, not even the pin asks. There just isn't a way to decrypt and encrypt.

### Version:
Last vendor a11 from motorola
Twrp 3.7.0
GSI: lineage 19.1 and 20
### Device:
guamp

**here** the twrp [logcat](https://github.com/TeamWin/android_device_motorola_guamp/files/10098871/logcat.txt) on a GSI android 12L

**Comment by RazaDroid** [comment]
Fixed
